### ISSUE TITLE
version property only accepts fully qualified versions

### ISSUE THREAD

**Issue by cheeseplus** [chef-cookbooks/habitat#26]
Trying to install a version using just the shortened SemVer doesn't work and even worse, silently fails.

```
hab_install 'install habitat' do
  version "0.14.0"
end
```
```
 - execute bash /tmp/kitchen/cache/hab-install.sh -v 0.14.0
```
Which seems to complete successfully as far as the resource is concerned but if after verifying that the hab binary is nowhere to be found and replicating the command you'll get

```
downloading https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-0.14.0-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
  to file /tmp/hab/hab-latest.tar.gz
trying wget...
ERROR 404

Either this means:
   - We do not support linux
   - We do not have an artifact for 0.14.0

Download URL: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-0.14.0-x86_64-linux.tar.gz
/tmp/kitchen/cache/hab-install.sh: 85: /tmp/kitchen/cache/hab-install.sh: stderr_results: parameter not set
```

The script we're using just doesn't seem to support that parameter and if using the fully qualified version `0.14.0/20161212214220` everything works as expected.

**Comment by mwrock** [comment]
It looks like this bug was recently introduced in the habitat repo with https://github.com/habitat-sh/habitat/commit/5ec8cf984cabbf376c3a82cf5e39d7575804485c and more recently reinforced with https://github.com/habitat-sh/habitat/commit/b4d8801ac65c645d2ac8880ce719510cd244748a which now explicitly states that using JUST version without the release is not supported.

When I added this resource property it was introduces along with https://github.com/habitat-sh/habitat/commit/580734bc813fd82a94ad1f8b6e46da26703c26a7 which would always get the latest from bintray but then run `hab install` to get the given version and it accepted both version only formats as well version/release.

Perhaps @smith and @fnichol encountred an issue with the above approach but it would be nice to support both formats which is what this cookbook claims to support.

**Comment by jtimberman** [comment]
As of habitat version 0.33 and the same version of this cookbook, specifying the version of habitat to install with `hab_install` is not supported.
