### ISSUE TITLE
Confused about what to do about hab user?

### ISSUE THREAD

**Issue by lnxchk** [chef-cookbooks/habitat#54]
### Cookbook version
0.36.0

### Chef-client version
12.21.14-1.el7

### Platform Details
CentOS 7.3.1611 in EC2

### Scenario:
I used the hab_install resource to install the habitat package, but it doesn't install a habitat user or note that one should be added otherwise? I don't see an option to include adding the user in the cookbook, though it appears in the tests.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
hab-sup(MR): Supervisor Member-ID 169d4a1a8fbb48268d0b531e9f4d9f98
hab-sup(MR): Starting learn-chef/habitatize
hab-sup(MR): Can't create directory /hab/svc/habitatize: hab-sup(UR)[src/sys/unix/users.rs:29:19]: Package requires user hab to exist, but it doesn't
hab-sup(MR): If this service is running as non-root, you'll need to create /hab/svc/habitatize and give the current user write access to it
hab-sup(MR): learn-chef/habitatize failed to start

**Comment by iennae** [comment]
Good catch. It looks like based on this recipe https://github.com/chef-cookbooks/habitat/blob/89f069695e4d78ca949d638739fa5eea89b92ef2/test/fixtures/cookbooks/test/recipes/config.rb that folks add the user separately. As I believe Ops is managing this cookbook, I'll let them update with expectations.

**Comment by iennae** [comment]
@jtimberman can you take a look at this question?

**Comment by jtimberman** [comment]
Do we have other cookbooks that create users? Generally speaking, operating systems/distributions create users from the package installation when necessary, and they usually have fixed, documented UIDs for those users to ensure there are no conflicts. I'm not sure if we should be creating the hab user in any of the resources in this cookbook. 

It may be appropriate to add a user creation property in the `hab_service` resource, since in Habitat the plan author can pick the user that their service runs as. The `hab` username is the default used by the Habitat project and `core-plans`, but it could easily be anything else. This would enable the authors of individual applications/habitat packaging to pick the user and ensure that Chef creates it correctly.

The test for the `hab` user in the service integration suite should probably be removed, as the services will fail to start up if the required user is not present anyway, and that user resource is in the `test` recipes (config and service).

**Comment by lnxchk** [comment]
I think it would be helpful as an option of the hab_service, or as a hab_user resource that can be altered by attributes. At the very least it should appear in the cookbook documentation as an unhandled pre-requisite for the default behavior of habitat so people can add it to their other recipes.

**Comment by jtimberman** [comment]
After much discussion amongst the Habitat core team, we determined that creating the user in the `hab_install` resource by default would be the least surprising thing, and if someone doesn't want the hab user created, they can opt out. 

PR #56 will add this functionality.
